language: java
jdk:
- oraclejdk8

services:
- docker

install:
- mvn install

script:
- docker build -t rest-in-cloud .
- docker tag rest-in-cloud:latest tommyziegler/rest-in-cloud:latest
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push tommyziegler/rest-in-cloud:latest