language: java
jdk:
- oraclejdk8

services:
- docker

install:
- mvn install

script:
- docker build -t blog .
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- docker tag rest-in-cloud:latest tommyziegler/rest-in-cloud:latest
- docker push tommyziegler/rest-in-cloud:latest

env:
  global:
  - secure: MGYArHuIZW9ht9OuqhrZ94LqtcTexsa7BqgThuh9qWLTkb0bjfzr/i99NGnAY+PoXwM+Nixqu31wcjE1X1zBQMliv6A09PQLnAyKXN7x6Wl0zlM14AF9AnKU0tBV4SYa/ge6KECveNwpWsJE4c/wQEYtN/NBAMdqvLN+XYP/MXkkHaDUWW5EbS52Vk9awygf+Ba8mCGR2LE3IcdzlhhdeUFpXLfdejBB5U+0ox8wC0CGYsATRin0G6CaxjMWGgECHKgA+EzKaY5+K28xVJbS3l3DUhsMPRTiP49XjiQpRD6ViUtGzzWzOSrE6HJQZrtpOpUULhrM0M97osJ4hSq2pdg+qCScKnWEJvmU3QAdMZqf2wZ2gRGqLHH7q0fE7RPQ6P/k0qXTlvtANxJ24F7S5B5vb7a1dc2UyrNXuNy37VXDeX99pgVI3MlBxg3SW3lIdlCOTlKLwiMxTea8ceE/kXL5mFSzmwfOgbU5le7d70rpWf+UI1fTw+VR5Pfco/Ha/vU8n8UUrqXoV+zsMU//i4WW7p8gaEmngOG4QXk9NBBYGR5ALkmQ4zxNAL1JEvcKCmWsZjqPLXhiGBs5OfXZafvM+40Ld2rQJmlBNbe5wgcy9JelNmCcfD1fZd25WoNrr3WQlxOQOap1du7t8AQ4skNtratmcDYkzAnrKKJyEd8=
  - secure: wU5ye0SXN7m7m4/gfLFPeRSCIalIUa6PjhWWlCKnXRcp1aRJEXgezXiVRvbDWCZ5rtG6nv4hyOvGayYvDxsPGzUYrELUJiPh9oZ7Ucnsf7ArKtG4hcH3ygNeNp6IR/zVsDzMb8+IYJXuTYFXF5WzASp0cWnQROPpsJkj+hes03TtqbGlxBKoyLTxg93Zzsp3pgeAH/m7dnFftMrguWtJs1RqKaXAxTfpqFZi68e8Ib/09CQrXiEQBRc1oZtfqqQhc3yNBRngZoGkVc70vTVKBCv8dEnnSM+cTklqiDgGWyiQdDyxDZEtC32qZcQ1Jz8btmQ+hJb9MCOTyVwY8IehjA9u5c8iK0TUR1TcTcRJ2R1OU+k+L1AOk5CJKoXBp3iruigdox/t8oCzj+/jWCxgP3X/bjv5JVLkcBwbI56j+MHoS9xhDRs+fVAtj9bMg/xrl/9QLQ+cWQ/JUzaPzK6TkVtAWZGFiJWcJRndZHd1LMenqCRWvPCya7cddcFrtDGAHi8CI3KGpTDVRsipy/dJXD1jjULyHoSt39CdKaIRwsjPzOWPOmXXoe7yuVaNyJAL/EoJYb5C5MsOAaqX0fUQnntVEUUZAz2rZZNwVr0Q+jiv4SSPBFmPp0JMLwt37k0UjCvD6NUOOMflTOcbA4nOG+C68hsbF+Wk7eyls2lZQvM=
  - secure: Z0vOoMTFi7zHPyEQr87IlJWwrBql9C/Xl9ToqJjTdqRJmiPLBj6qg3ChXY9BJ/eJWFUHZn0pVNI4iaulc2hNwIeCq8R1Ky2EyTGdUola+2V3Q/04dcTdHb+8ls4lvqxJbBfwQP8GSrMoiFdrv6g7x5Bij3d0k20V+6oXLkJO+Xv0keqBeoMBNmhHsmp5j6K6CvMf39SfSwHnLMdz94h8Q1jFpP4GeRTEGx4CUgkGYtNMXAg0bKhawQPYoPNkSEnkIsIiDV9+Mx7qkd6yIOzvNZI4S1ynCnecJsyGiUdohDZTSY9TVPBLc/IBZ3GyK6JONz2Hi4zKOVBoN1S7oZJHJtm7Rk7aNcA1jCvU3EX5pJd6vpH6XwgyRXAJFfK7QHKrsa95DQHkKveTNPyv3GCy85IDwxAKiOkFzAVewgJvu7HfbKrc11SEluESmtLr+2U3J3Lz8/3Lic22vwnkHAIFUGjfEVOdpV2j+PgCfY7eRhjggHnnZesNgEAq2aG+YGzaKpOdSDIIC8zIH8jJxas1GwU6znXZV6I5MYf+q19Kabo0rB0dAlijV+6YV1O2WCTy9Ltsf7ksqTO0jlQjL+PJsvayebB6FR4Fn5rU4/80hSXcufszeS31NOQv3hMkZCzww4PUkaHroSn7kic8APr7S97+32EWyQP5529109g8ESc=
